import { user } from "@shared/api/local/schemas/user.schema";
import {
  foreignKey,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";
import { blockPack } from "./blockPack.schema";

export const blockGroup = sqliteTable(
  "BlockGroupTable",
  {
    id: text("id").primaryKey(),
    ownerPublicId: text("owner_public_id")
      .notNull()
      .references(() => user.publicId, {
        onUpdate: "cascade",
        onDelete: "cascade",
      }),
    blockPackId: text("block_pack_id")
      .notNull()
      .references(() => blockPack.id, {
        onUpdate: "cascade",
        onDelete: "cascade",
      }),
    prevBlockGroupId: text("prev_block_group_id"),
    syncBlockGroupId: text("sync_block_group_id"),
    size: integer("size").notNull().default(0),
    deletedAt: integer("deleted_at", { mode: "timestamp" }),
    updatedAt: integer("updated_at", { mode: "timestamp" })
      .notNull()
      .default(new Date()),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(new Date()),
  },
  table => [
    uniqueIndex("block_group_unique_idx_block_pack_id_prev_block_group_id").on(
      table.blockPackId,
      table.prevBlockGroupId
    ), // 'where deleted_at IS NULL' should be added to the sql file which generated by the drizzle-kit
    foreignKey({
      columns: [table.prevBlockGroupId],
      foreignColumns: [table.id],
      name: "block_group_fk_prev_block_group_id",
    })
      .onUpdate("cascade")
      .onDelete("cascade"),
  ]
);
