import { user } from "@shared/api/local/schemas/user.schema";
import {
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

// the same schemas as the rootShelf in api interface
export const rootShelf = sqliteTable(
  "RootShelfTable",
  {
    id: text("id").primaryKey(),
    ownerPublicId: text("owner_public_id")
      .notNull()
      .references(() => user.publicId, {
        onUpdate: "cascade",
        onDelete: "cascade",
      }),
    name: text("name").notNull().default("undefined"),
    subShelfCount: integer("sub_shelf_count").notNull().default(0),
    itemCount: integer("item_count").notNull().default(0),
    lastAnalyzedAt: integer("last_analyzed_count", {
      mode: "timestamp",
    })
      .notNull()
      .default(new Date()),
    deletedAt: integer("deleted_at", { mode: "timestamp" })
      .notNull()
      .default(new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp" })
      .notNull()
      .default(new Date()),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(new Date()),
  },
  table => [
    uniqueIndex("root_shelf_unique_idx_owner_id_name").on(table.name), // 'where deleted_at IS NULL' should be added to the sql file which generated by the drizzle-kit
  ]
);
