import {
  foreignKey,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";
import { rootShelf } from "./rootShelf.schema";

// the same schemas as the subShelf in api interface
export const subShelf = sqliteTable(
  "SubShelfTable",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull().default("undefined"),
    rootShelfId: text("root_shelf_id")
      .notNull()
      .references(() => rootShelf.id, {
        onUpdate: "cascade",
        onDelete: "cascade",
      }),
    prevSubShelfId: text("prev_sub_shelf_id"),
    path: text("path").notNull().default("[]"), // JSON string, but formed by uuid array
    deletedAt: integer("deleted_at", { mode: "timestamp" }),
    updatedAt: integer("updated_at", { mode: "timestamp" })
      .notNull()
      .default(new Date()),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(new Date()),
  },
  table => [
    uniqueIndex("sub_shelf_unique_idx_name_root_shelf_id_path").on(
      table.name,
      table.rootShelfId,
      table.path
    ), // 'where deleted_at IS NULL' should be added to the sql file which generated by the drizzle-kit
    foreignKey({
      columns: [table.prevSubShelfId],
      foreignColumns: [table.id],
      name: "sub_shelf_fk_prev_sub_shelf_id",
    })
      .onUpdate("cascade")
      .onDelete("cascade"),
  ]
);
