import {
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

// the same schemas as the subShelf in api interface
export const subShelf = sqliteTable(
  "SubShelfTable",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull().default("undefined"),
    rootShelfId: text("root_shelf_id").notNull(),
    prevSubShelfId: text("prev_sub_shelf_id").notNull(),
    path: text("path").notNull().default("[]"), // JSON string, but formed by uuid array
    deletedAt: integer("deleted_at", { mode: "timestamp" }),
    updatedAt: integer("updated_at", { mode: "timestamp" })
      .notNull()
      .default(new Date()),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(new Date()),
  },
  table => [
    uniqueIndex("sub_shelf_unique_idx_name_root_shelf_id_path").on(
      table.name,
      table.rootShelfId,
      table.path
    ), // 'where deleted_at IS NULL' should be added to the sql file which generated by the drizzle-kit
  ]
);
