import localMigrationJournal from "./migrations/meta/_journal.json";

const migrationSqlModules = import.meta.glob("./migrations/*.sql", {
  eager: true,
  query: "?raw",
  import: "default",
}) as Record<string, string>;

type MigrationEntry = {
  idx: number;
  tag: string;
  versionNumber: number;
  sqlContent: string;
  statements: string[];
};

type MigrationResult = {
  appliedTags: string[];
  finalVersion: number;
};

type LocalDBMigratorClient = {
  run: (query: string) => Promise<unknown>;
  all: <T = unknown>(query: string) => Promise<T[]>;
};

const normalizeVersionNumber = (version: number | null | undefined): number => {
  if (version === null || version === undefined) return 0;
  if (!Number.isFinite(version)) return 0;
  return Math.trunc(version);
};

const getOrderedMigrations = (): MigrationEntry[] => {
  const sqlByTag = new Map<string, string>();
  for (const [path, sqlContent] of Object.entries(migrationSqlModules)) {
    const fileName = path.split("/").pop();
    if (!fileName || !fileName.endsWith(".sql")) continue;
    const tag = fileName.replace(".sql", "");
    if (!tag) continue;
    sqlByTag.set(tag, sqlContent);
  }

  const journalEntries = (localMigrationJournal.entries ?? []) as {
    idx: number;
    tag: string;
  }[];

  return [...journalEntries]
    .sort((a, b) => a.idx - b.idx)
    .map(entry => {
      const sqlContent = sqlByTag.get(entry.tag);
      if (!sqlContent) {
        throw new Error(
          `missing local migration SQL file for tag "${entry.tag}" in shared/api/local/migrations`
        );
      }

      const [prefix] = entry.tag.split("_");
      const versionNumber =
        prefix && /^\d+$/.test(prefix) ? Number(prefix) : -1;
      return {
        idx: entry.idx,
        tag: entry.tag,
        versionNumber,
        sqlContent,
        statements: sqlContent
          .split("--> statement-breakpoint")
          .map(statement => statement.trim())
          .filter(Boolean),
      };
    });
};

export class LocalDBMigrator {
  private runningMigrationPromise: Promise<MigrationResult> | null = null;
  private readonly localDB: LocalDBMigratorClient;
  private MaxErrorMessageDepth;

  constructor(
    localDB: LocalDBMigratorClient,
    maxErrorMessageDepth: number = 10
  ) {
    this.localDB = localDB;
    this.MaxErrorMessageDepth = maxErrorMessageDepth;
  }

  // get the largest migration number from the migration files in shared/api/local/migrations/
  // but return the largest migration number + 1 as the latest version since the user_version from SQLite PRAGMA forced to start from 0
  public getLatestMigrationVersion = (): number => {
    const orderedMigrations = getOrderedMigrations();
    const latestMigration = orderedMigrations[orderedMigrations.length - 1];
    if (!latestMigration) return 0;
    return latestMigration.versionNumber + 1;
  };

  public ensureMigrated = async (options?: {
    currentVersion?: number | null;
    targetVersion?: number | null;
  }): Promise<MigrationResult> => {
    if (this.runningMigrationPromise) return this.runningMigrationPromise;

    this.runningMigrationPromise = (async () => {
      const orderedMigrations = getOrderedMigrations();
      const currentVersionNumber = normalizeVersionNumber(
        options?.currentVersion
      );
      const targetVersionNumber =
        options?.targetVersion === undefined || options?.targetVersion === null
          ? Number.POSITIVE_INFINITY
          : normalizeVersionNumber(options.targetVersion);

      const pendingMigrations = orderedMigrations.filter(migration => {
        const migrationVersion = migration.versionNumber + 1;
        if (migrationVersion <= currentVersionNumber) return false;
        if (migrationVersion > targetVersionNumber) return false;
        return true;
      });

      const appliedTags: string[] = [];
      for (const migration of pendingMigrations) {
        for (const statement of migration.statements) {
          // keep migration files generated by drizzle-kit untouched.
          // sqlocal cannot bind placeholders in raw SQL files, so we normalize
          // static boolean partial-index predicates to a literal value.
          const normalizedStatement = statement.replace(/\=\s*\?/g, "= 1");
          try {
            await this.localDB.run(normalizedStatement);
          } catch (error) {
            let nestedError: unknown = error;
            let errorMessages = "";
            for (let depth = 0; depth < this.MaxErrorMessageDepth; depth += 1) {
              if (!(nestedError instanceof Error)) break;
              errorMessages += ` ${nestedError.message}`;
              nestedError = (nestedError as { cause?: unknown }).cause;
            }

            const statementTrimmed = normalizedStatement.trim();
            const isCreateStatement =
              /^CREATE\s+(TABLE|UNIQUE\s+INDEX|INDEX|VIEW)\s+/i.test(
                statementTrimmed
              );
            const isDropTableStatement = /^DROP\s+TABLE\s+/i.test(
              statementTrimmed
            );
            const isAlterTableAddColumnStatement =
              /^ALTER\s+TABLE\s+.+\s+ADD\s+(COLUMN\s+)?/i.test(
                statementTrimmed
              );
            const isAlreadyExistsError = /already exists/i.test(errorMessages);
            const isNoSuchTableError = /no such table/i.test(errorMessages);
            const isDuplicateColumnError = /duplicate column name/i.test(
              errorMessages
            );

            if (
              (!isCreateStatement || !isAlreadyExistsError) &&
              (!isDropTableStatement || !isNoSuchTableError) &&
              (!isAlterTableAddColumnStatement || !isDuplicateColumnError)
            )
              throw error;
          }
        }
        appliedTags.push(migration.tag);
      }

      const finalVersionNumber =
        pendingMigrations.length > 0
          ? pendingMigrations[pendingMigrations.length - 1].versionNumber + 1
          : currentVersionNumber;

      return {
        appliedTags,
        finalVersion: finalVersionNumber,
      };
    })().finally(() => {
      this.runningMigrationPromise = null;
    });

    return this.runningMigrationPromise;
  };
}
