import { exec } from "./db";
import localMigrationJournal from "./migrations/meta/_journal.json";

type OrderedMigration = {
  idx: number;
  tag: string;
  versionNumber: number;
  version: string;
  sqlContent: string;
  statements: string[];
};

const migrationSqlModules = import.meta.glob("./migrations/*.sql", {
  eager: true,
  query: "?raw",
  import: "default",
}) as Record<string, string>;

let runningMigrationPromise: Promise<{
  appliedTags: string[];
  finalVersion: string;
}> | null = null;

function splitMigrationSqlStatements(sqlFileContent: string): string[] {
  return sqlFileContent
    .split("--> statement-breakpoint")
    .map(statement => statement.trim())
    .filter(Boolean);
}

function getMigrationTagFromPath(path: string): string | null {
  const fileName = path.split("/").pop();
  if (!fileName || !fileName.endsWith(".sql")) return null;
  return fileName.replace(".sql", "");
}

function parseVersionNumberFromTag(tag: string): number {
  const [prefix] = tag.split("_");
  if (!prefix || !/^\d+$/.test(prefix)) return -1;
  return Number(prefix);
}

function normalizeVersionNumber(version: string | null | undefined): number {
  if (version === null || version === undefined) return -1;
  if (version === "-1") return -1;
  if (!/^\d+$/.test(version)) return -1;
  return Number(version);
}

function formatVersionNumber(versionNumber: number): string {
  if (versionNumber < 0) return "-1";
  return String(versionNumber).padStart(4, "0");
}

function getOrderedMigrations(): OrderedMigration[] {
  const sqlByTag = new Map<string, string>();
  for (const [path, sqlContent] of Object.entries(migrationSqlModules)) {
    const tag = getMigrationTagFromPath(path);
    if (!tag) continue;
    sqlByTag.set(tag, sqlContent);
  }

  const journalEntries = (localMigrationJournal.entries ?? []) as {
    idx: number;
    tag: string;
  }[];

  return [...journalEntries]
    .sort((a, b) => a.idx - b.idx)
    .map(entry => {
      const sqlContent = sqlByTag.get(entry.tag);
      if (!sqlContent) {
        throw new Error(
          `missing local migration SQL file for tag "${entry.tag}" in shared/api/local/migrations`
        );
      }

      const versionNumber = parseVersionNumberFromTag(entry.tag);
      return {
        idx: entry.idx,
        tag: entry.tag,
        versionNumber,
        version: formatVersionNumber(versionNumber),
        sqlContent,
        statements: splitMigrationSqlStatements(sqlContent),
      };
    });
}

function isCreateStatement(statement: string): boolean {
  return /^CREATE\s+(TABLE|UNIQUE\s+INDEX|INDEX|VIEW)\s+/i.test(
    statement.trim()
  );
}

function isDropTableStatement(statement: string): boolean {
  return /^DROP\s+TABLE\s+/i.test(statement.trim());
}

function isAlreadyExistsError(error: unknown): boolean {
  return error instanceof Error && /already exists/i.test(error.message);
}

function isNoSuchTableError(error: unknown): boolean {
  return error instanceof Error && /no such table/i.test(error.message);
}

function isIgnorableMigrationError(statement: string, error: unknown): boolean {
  if (isCreateStatement(statement) && isAlreadyExistsError(error)) return true;
  if (isDropTableStatement(statement) && isNoSuchTableError(error)) return true;
  return false;
}

async function applyMigrationStatements(statements: string[]): Promise<void> {
  const normalizeStatement = (statement: string): string => {
    // Keep migration files generated by drizzle-kit untouched.
    // sqlocal cannot bind placeholders in raw SQL files, so we normalize
    // static boolean partial-index predicates to a literal value.
    return statement.replace(/\=\s*\?/g, "= 1");
  };

  for (const statement of statements) {
    const normalizedStatement = normalizeStatement(statement);
    try {
      await exec(normalizedStatement, [], "run");
    } catch (error) {
      if (isIgnorableMigrationError(normalizedStatement, error)) continue;
      throw error;
    }
  }
}

export function getLatestLocalDBMigrationVersion(): string {
  const orderedMigrations = getOrderedMigrations();
  const latestMigration = orderedMigrations[orderedMigrations.length - 1];
  if (!latestMigration) return "-1";
  return latestMigration.version;
}

export function getPendingLocalDBMigrationTags(
  currentVersion: string | null | undefined,
  targetVersion?: string | null
): string[] {
  const orderedMigrations = getOrderedMigrations();
  const currentVersionNumber = normalizeVersionNumber(currentVersion);
  const targetVersionNumber =
    targetVersion === undefined || targetVersion === null
      ? Number.POSITIVE_INFINITY
      : normalizeVersionNumber(targetVersion);

  return orderedMigrations
    .filter(migration => {
      if (migration.versionNumber <= currentVersionNumber) return false;
      if (migration.versionNumber > targetVersionNumber) return false;
      return true;
    })
    .map(migration => migration.tag);
}

export async function ensureLocalDBMigrated(options?: {
  currentVersion?: string | null;
  targetVersion?: string | null;
}): Promise<{ appliedTags: string[]; finalVersion: string }> {
  if (runningMigrationPromise) return runningMigrationPromise;

  runningMigrationPromise = (async () => {
    const orderedMigrations = getOrderedMigrations();
    const currentVersionNumber = normalizeVersionNumber(
      options?.currentVersion
    );
    const targetVersionNumber =
      options?.targetVersion === undefined || options?.targetVersion === null
        ? Number.POSITIVE_INFINITY
        : normalizeVersionNumber(options.targetVersion);

    const pendingMigrations = orderedMigrations.filter(migration => {
      if (migration.versionNumber <= currentVersionNumber) return false;
      if (migration.versionNumber > targetVersionNumber) return false;
      return true;
    });

    const appliedTags: string[] = [];
    for (const migration of pendingMigrations) {
      await applyMigrationStatements(migration.statements);
      appliedTags.push(migration.tag);
    }

    const finalVersionNumber =
      pendingMigrations.length > 0
        ? pendingMigrations[pendingMigrations.length - 1].versionNumber
        : currentVersionNumber;

    return {
      appliedTags,
      finalVersion: formatVersionNumber(finalVersionNumber),
    };
  })().finally(() => {
    runningMigrationPromise = null;
  });

  return runningMigrationPromise;
}

export async function ensureLocalDBReadyForWrites(options?: {
  currentVersion?: string | null;
  targetVersion?: string | null;
}): Promise<{ appliedTags: string[]; finalVersion: string }> {
  const currentVersion = options?.currentVersion ?? "-1";
  const targetVersion = options?.targetVersion ?? getLatestLocalDBMigrationVersion();

  const migrationResult = await ensureLocalDBMigrated({
    currentVersion,
    targetVersion,
  });

  try {
    await exec(`SELECT 1 FROM "UserTable" LIMIT 1`, [], "all");
    await exec(`SELECT 1 FROM "TransactionTable" LIMIT 1`, [], "all");
    return migrationResult;
  } catch {
    return await ensureLocalDBMigrated({
      currentVersion: "-1",
      targetVersion,
    });
  }
}
