# =============== Search SortBy & Input =============== #

enum SearchMaterialSortBy {
  RELEVANCE
  NAME
  SIZE
  CONTENT_TYPE
  LAST_UPDATE
  CREATED_AT
}

input SearchMaterialInput {
  parentSubShelfId: UUID
  rootShelfId: UUID
  query: String!
  isDeletedAt: Boolean
  after: String
  first: Int = 10
  sortBy: SearchMaterialSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchMaterialCursorFields {
  id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchMaterialEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateMaterial!
}

type SearchMaterialConnection implements SearchConnection {
  searchEdges: [SearchMaterialEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}
