# =============== Search SortBy & Input =============== #

enum SearchBlockPackSortBy {
  RELEVANCE
  NAME
  BLOCK_COUNT
  LAST_UPDATE
  CREATED_AT
}

input SearchBlockPackInput {
  parentSubShelfId: UUID
  rootShelfId: UUID
  query: String!
  isDeletedAt: Boolean
  after: String
  first: Int = 10
  sortBy: SearchBlockPackSortBy = RELEVANCE
  sortOrder: SearchSortOrder = DESC
}

# =============== Search Cursor Fields =============== #

input SearchBlockPackCursorFields {
  id: UUID!
}

# =============== Search Edge & Connection =============== #

type SearchBlockPackEdge implements SearchEdge {
  encodedSearchCursor: String!
  node: PrivateBlockPack!
}

type SearchBlockPackConnection implements SearchConnection {
  searchEdges: [SearchBlockPackEdge!]!
  searchPageInfo: SearchPageInfo!
  totalCount: Int!
  searchTime: Float!
}
