/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RootRouteImport } from './routes/_root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RootRoutinesRouteImport } from './routes/_root.routines'
import { Route as RootPrivacyPolicyRouteImport } from './routes/_root.privacy-policy'
import { Route as RootPlaygroundRouteImport } from './routes/_root.playground'
import { Route as RootMaterialViewerRouteImport } from './routes/_root.material-viewer'
import { Route as RootIntroductionRouteImport } from './routes/_root.introduction'
import { Route as RootDashboardRouteImport } from './routes/_root.dashboard'
import { Route as RootBlockPackEditorRouteImport } from './routes/_root.block-pack-editor'
import { Route as RootAdminRouteImport } from './routes/_root.admin'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgetPasswordRouteImport } from './routes/_auth.forgetPassword'
import { Route as RootRoutinesIndexRouteImport } from './routes/_root.routines.index'
import { Route as RootMaterialViewerIndexRouteImport } from './routes/_root.material-viewer.index'
import { Route as RootDashboardIndexRouteImport } from './routes/_root.dashboard.index'
import { Route as RootBlockPackEditorIndexRouteImport } from './routes/_root.block-pack-editor.index'
import { Route as RootRoutinesStationIdRouteImport } from './routes/_root.routines.$stationId'
import { Route as RootMaterialViewerMaterialIdRouteImport } from './routes/_root.material-viewer.$materialId'
import { Route as RootBlockPackEditorBlockPackIdRouteImport } from './routes/_root.block-pack-editor.$blockPackId'
import { Route as AuthRedirectXRouteImport } from './routes/_auth.redirect.x'
import { Route as AuthRedirectGoogleRouteImport } from './routes/_auth.redirect.google'
import { Route as AuthRedirectErrorRouteImport } from './routes/_auth.redirect.error'

const RootRoute = RootRouteImport.update({
  id: '/_root',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RootRoutinesRoute = RootRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => RootRoute,
} as any)
const RootPrivacyPolicyRoute = RootPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => RootRoute,
} as any)
const RootPlaygroundRoute = RootPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => RootRoute,
} as any)
const RootMaterialViewerRoute = RootMaterialViewerRouteImport.update({
  id: '/material-viewer',
  path: '/material-viewer',
  getParentRoute: () => RootRoute,
} as any)
const RootIntroductionRoute = RootIntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => RootRoute,
} as any)
const RootDashboardRoute = RootDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RootRoute,
} as any)
const RootBlockPackEditorRoute = RootBlockPackEditorRouteImport.update({
  id: '/block-pack-editor',
  path: '/block-pack-editor',
  getParentRoute: () => RootRoute,
} as any)
const RootAdminRoute = RootAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => RootRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forgetPassword',
  path: '/forgetPassword',
  getParentRoute: () => AuthRoute,
} as any)
const RootRoutinesIndexRoute = RootRoutinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootRoutinesRoute,
} as any)
const RootMaterialViewerIndexRoute = RootMaterialViewerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootMaterialViewerRoute,
} as any)
const RootDashboardIndexRoute = RootDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootDashboardRoute,
} as any)
const RootBlockPackEditorIndexRoute =
  RootBlockPackEditorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RootBlockPackEditorRoute,
  } as any)
const RootRoutinesStationIdRoute = RootRoutinesStationIdRouteImport.update({
  id: '/$stationId',
  path: '/$stationId',
  getParentRoute: () => RootRoutinesRoute,
} as any)
const RootMaterialViewerMaterialIdRoute =
  RootMaterialViewerMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => RootMaterialViewerRoute,
  } as any)
const RootBlockPackEditorBlockPackIdRoute =
  RootBlockPackEditorBlockPackIdRouteImport.update({
    id: '/$blockPackId',
    path: '/$blockPackId',
    getParentRoute: () => RootBlockPackEditorRoute,
  } as any)
const AuthRedirectXRoute = AuthRedirectXRouteImport.update({
  id: '/redirect/x',
  path: '/redirect/x',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRedirectGoogleRoute = AuthRedirectGoogleRouteImport.update({
  id: '/redirect/google',
  path: '/redirect/google',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRedirectErrorRoute = AuthRedirectErrorRouteImport.update({
  id: '/redirect/error',
  path: '/redirect/error',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgetPassword': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin': typeof RootAdminRoute
  '/block-pack-editor': typeof RootBlockPackEditorRouteWithChildren
  '/dashboard': typeof RootDashboardRouteWithChildren
  '/introduction': typeof RootIntroductionRoute
  '/material-viewer': typeof RootMaterialViewerRouteWithChildren
  '/playground': typeof RootPlaygroundRoute
  '/privacy-policy': typeof RootPrivacyPolicyRoute
  '/routines': typeof RootRoutinesRouteWithChildren
  '/redirect/error': typeof AuthRedirectErrorRoute
  '/redirect/google': typeof AuthRedirectGoogleRoute
  '/redirect/x': typeof AuthRedirectXRoute
  '/block-pack-editor/$blockPackId': typeof RootBlockPackEditorBlockPackIdRoute
  '/material-viewer/$materialId': typeof RootMaterialViewerMaterialIdRoute
  '/routines/$stationId': typeof RootRoutinesStationIdRoute
  '/block-pack-editor/': typeof RootBlockPackEditorIndexRoute
  '/dashboard/': typeof RootDashboardIndexRoute
  '/material-viewer/': typeof RootMaterialViewerIndexRoute
  '/routines/': typeof RootRoutinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgetPassword': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin': typeof RootAdminRoute
  '/introduction': typeof RootIntroductionRoute
  '/playground': typeof RootPlaygroundRoute
  '/privacy-policy': typeof RootPrivacyPolicyRoute
  '/redirect/error': typeof AuthRedirectErrorRoute
  '/redirect/google': typeof AuthRedirectGoogleRoute
  '/redirect/x': typeof AuthRedirectXRoute
  '/block-pack-editor/$blockPackId': typeof RootBlockPackEditorBlockPackIdRoute
  '/material-viewer/$materialId': typeof RootMaterialViewerMaterialIdRoute
  '/routines/$stationId': typeof RootRoutinesStationIdRoute
  '/block-pack-editor': typeof RootBlockPackEditorIndexRoute
  '/dashboard': typeof RootDashboardIndexRoute
  '/material-viewer': typeof RootMaterialViewerIndexRoute
  '/routines': typeof RootRoutinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_root': typeof RootRouteWithChildren
  '/_auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_root/admin': typeof RootAdminRoute
  '/_root/block-pack-editor': typeof RootBlockPackEditorRouteWithChildren
  '/_root/dashboard': typeof RootDashboardRouteWithChildren
  '/_root/introduction': typeof RootIntroductionRoute
  '/_root/material-viewer': typeof RootMaterialViewerRouteWithChildren
  '/_root/playground': typeof RootPlaygroundRoute
  '/_root/privacy-policy': typeof RootPrivacyPolicyRoute
  '/_root/routines': typeof RootRoutinesRouteWithChildren
  '/_auth/redirect/error': typeof AuthRedirectErrorRoute
  '/_auth/redirect/google': typeof AuthRedirectGoogleRoute
  '/_auth/redirect/x': typeof AuthRedirectXRoute
  '/_root/block-pack-editor/$blockPackId': typeof RootBlockPackEditorBlockPackIdRoute
  '/_root/material-viewer/$materialId': typeof RootMaterialViewerMaterialIdRoute
  '/_root/routines/$stationId': typeof RootRoutinesStationIdRoute
  '/_root/block-pack-editor/': typeof RootBlockPackEditorIndexRoute
  '/_root/dashboard/': typeof RootDashboardIndexRoute
  '/_root/material-viewer/': typeof RootMaterialViewerIndexRoute
  '/_root/routines/': typeof RootRoutinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgetPassword'
    | '/login'
    | '/register'
    | '/admin'
    | '/block-pack-editor'
    | '/dashboard'
    | '/introduction'
    | '/material-viewer'
    | '/playground'
    | '/privacy-policy'
    | '/routines'
    | '/redirect/error'
    | '/redirect/google'
    | '/redirect/x'
    | '/block-pack-editor/$blockPackId'
    | '/material-viewer/$materialId'
    | '/routines/$stationId'
    | '/block-pack-editor/'
    | '/dashboard/'
    | '/material-viewer/'
    | '/routines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgetPassword'
    | '/login'
    | '/register'
    | '/admin'
    | '/introduction'
    | '/playground'
    | '/privacy-policy'
    | '/redirect/error'
    | '/redirect/google'
    | '/redirect/x'
    | '/block-pack-editor/$blockPackId'
    | '/material-viewer/$materialId'
    | '/routines/$stationId'
    | '/block-pack-editor'
    | '/dashboard'
    | '/material-viewer'
    | '/routines'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_root'
    | '/_auth/forgetPassword'
    | '/_auth/login'
    | '/_auth/register'
    | '/_root/admin'
    | '/_root/block-pack-editor'
    | '/_root/dashboard'
    | '/_root/introduction'
    | '/_root/material-viewer'
    | '/_root/playground'
    | '/_root/privacy-policy'
    | '/_root/routines'
    | '/_auth/redirect/error'
    | '/_auth/redirect/google'
    | '/_auth/redirect/x'
    | '/_root/block-pack-editor/$blockPackId'
    | '/_root/material-viewer/$materialId'
    | '/_root/routines/$stationId'
    | '/_root/block-pack-editor/'
    | '/_root/dashboard/'
    | '/_root/material-viewer/'
    | '/_root/routines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  RootRoute: typeof RootRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_root': {
      id: '/_root'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root/routines': {
      id: '/_root/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RootRoutinesRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/privacy-policy': {
      id: '/_root/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof RootPrivacyPolicyRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/playground': {
      id: '/_root/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof RootPlaygroundRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/material-viewer': {
      id: '/_root/material-viewer'
      path: '/material-viewer'
      fullPath: '/material-viewer'
      preLoaderRoute: typeof RootMaterialViewerRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/introduction': {
      id: '/_root/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof RootIntroductionRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/dashboard': {
      id: '/_root/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof RootDashboardRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/block-pack-editor': {
      id: '/_root/block-pack-editor'
      path: '/block-pack-editor'
      fullPath: '/block-pack-editor'
      preLoaderRoute: typeof RootBlockPackEditorRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/admin': {
      id: '/_root/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof RootAdminRouteImport
      parentRoute: typeof RootRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgetPassword': {
      id: '/_auth/forgetPassword'
      path: '/forgetPassword'
      fullPath: '/forgetPassword'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_root/routines/': {
      id: '/_root/routines/'
      path: '/'
      fullPath: '/routines/'
      preLoaderRoute: typeof RootRoutinesIndexRouteImport
      parentRoute: typeof RootRoutinesRoute
    }
    '/_root/material-viewer/': {
      id: '/_root/material-viewer/'
      path: '/'
      fullPath: '/material-viewer/'
      preLoaderRoute: typeof RootMaterialViewerIndexRouteImport
      parentRoute: typeof RootMaterialViewerRoute
    }
    '/_root/dashboard/': {
      id: '/_root/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof RootDashboardIndexRouteImport
      parentRoute: typeof RootDashboardRoute
    }
    '/_root/block-pack-editor/': {
      id: '/_root/block-pack-editor/'
      path: '/'
      fullPath: '/block-pack-editor/'
      preLoaderRoute: typeof RootBlockPackEditorIndexRouteImport
      parentRoute: typeof RootBlockPackEditorRoute
    }
    '/_root/routines/$stationId': {
      id: '/_root/routines/$stationId'
      path: '/$stationId'
      fullPath: '/routines/$stationId'
      preLoaderRoute: typeof RootRoutinesStationIdRouteImport
      parentRoute: typeof RootRoutinesRoute
    }
    '/_root/material-viewer/$materialId': {
      id: '/_root/material-viewer/$materialId'
      path: '/$materialId'
      fullPath: '/material-viewer/$materialId'
      preLoaderRoute: typeof RootMaterialViewerMaterialIdRouteImport
      parentRoute: typeof RootMaterialViewerRoute
    }
    '/_root/block-pack-editor/$blockPackId': {
      id: '/_root/block-pack-editor/$blockPackId'
      path: '/$blockPackId'
      fullPath: '/block-pack-editor/$blockPackId'
      preLoaderRoute: typeof RootBlockPackEditorBlockPackIdRouteImport
      parentRoute: typeof RootBlockPackEditorRoute
    }
    '/_auth/redirect/x': {
      id: '/_auth/redirect/x'
      path: '/redirect/x'
      fullPath: '/redirect/x'
      preLoaderRoute: typeof AuthRedirectXRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/redirect/google': {
      id: '/_auth/redirect/google'
      path: '/redirect/google'
      fullPath: '/redirect/google'
      preLoaderRoute: typeof AuthRedirectGoogleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/redirect/error': {
      id: '/_auth/redirect/error'
      path: '/redirect/error'
      fullPath: '/redirect/error'
      preLoaderRoute: typeof AuthRedirectErrorRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRedirectErrorRoute: typeof AuthRedirectErrorRoute
  AuthRedirectGoogleRoute: typeof AuthRedirectGoogleRoute
  AuthRedirectXRoute: typeof AuthRedirectXRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRedirectErrorRoute: AuthRedirectErrorRoute,
  AuthRedirectGoogleRoute: AuthRedirectGoogleRoute,
  AuthRedirectXRoute: AuthRedirectXRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface RootBlockPackEditorRouteChildren {
  RootBlockPackEditorBlockPackIdRoute: typeof RootBlockPackEditorBlockPackIdRoute
  RootBlockPackEditorIndexRoute: typeof RootBlockPackEditorIndexRoute
}

const RootBlockPackEditorRouteChildren: RootBlockPackEditorRouteChildren = {
  RootBlockPackEditorBlockPackIdRoute: RootBlockPackEditorBlockPackIdRoute,
  RootBlockPackEditorIndexRoute: RootBlockPackEditorIndexRoute,
}

const RootBlockPackEditorRouteWithChildren =
  RootBlockPackEditorRoute._addFileChildren(RootBlockPackEditorRouteChildren)

interface RootDashboardRouteChildren {
  RootDashboardIndexRoute: typeof RootDashboardIndexRoute
}

const RootDashboardRouteChildren: RootDashboardRouteChildren = {
  RootDashboardIndexRoute: RootDashboardIndexRoute,
}

const RootDashboardRouteWithChildren = RootDashboardRoute._addFileChildren(
  RootDashboardRouteChildren,
)

interface RootMaterialViewerRouteChildren {
  RootMaterialViewerMaterialIdRoute: typeof RootMaterialViewerMaterialIdRoute
  RootMaterialViewerIndexRoute: typeof RootMaterialViewerIndexRoute
}

const RootMaterialViewerRouteChildren: RootMaterialViewerRouteChildren = {
  RootMaterialViewerMaterialIdRoute: RootMaterialViewerMaterialIdRoute,
  RootMaterialViewerIndexRoute: RootMaterialViewerIndexRoute,
}

const RootMaterialViewerRouteWithChildren =
  RootMaterialViewerRoute._addFileChildren(RootMaterialViewerRouteChildren)

interface RootRoutinesRouteChildren {
  RootRoutinesStationIdRoute: typeof RootRoutinesStationIdRoute
  RootRoutinesIndexRoute: typeof RootRoutinesIndexRoute
}

const RootRoutinesRouteChildren: RootRoutinesRouteChildren = {
  RootRoutinesStationIdRoute: RootRoutinesStationIdRoute,
  RootRoutinesIndexRoute: RootRoutinesIndexRoute,
}

const RootRoutinesRouteWithChildren = RootRoutinesRoute._addFileChildren(
  RootRoutinesRouteChildren,
)

interface RootRouteChildren {
  RootAdminRoute: typeof RootAdminRoute
  RootBlockPackEditorRoute: typeof RootBlockPackEditorRouteWithChildren
  RootDashboardRoute: typeof RootDashboardRouteWithChildren
  RootIntroductionRoute: typeof RootIntroductionRoute
  RootMaterialViewerRoute: typeof RootMaterialViewerRouteWithChildren
  RootPlaygroundRoute: typeof RootPlaygroundRoute
  RootPrivacyPolicyRoute: typeof RootPrivacyPolicyRoute
  RootRoutinesRoute: typeof RootRoutinesRouteWithChildren
}

const RootRouteChildren: RootRouteChildren = {
  RootAdminRoute: RootAdminRoute,
  RootBlockPackEditorRoute: RootBlockPackEditorRouteWithChildren,
  RootDashboardRoute: RootDashboardRouteWithChildren,
  RootIntroductionRoute: RootIntroductionRoute,
  RootMaterialViewerRoute: RootMaterialViewerRouteWithChildren,
  RootPlaygroundRoute: RootPlaygroundRoute,
  RootPrivacyPolicyRoute: RootPrivacyPolicyRoute,
  RootRoutinesRoute: RootRoutinesRouteWithChildren,
}

const RootRouteWithChildren = RootRoute._addFileChildren(RootRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  RootRoute: RootRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
