/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RootRouteImport } from './routes/_root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RootPrivacyPolicyRouteImport } from './routes/_root.privacy-policy'
import { Route as RootPlaygroundRouteImport } from './routes/_root.playground'
import { Route as RootMaterialEditorRouteImport } from './routes/_root.material-editor'
import { Route as RootIntroductionRouteImport } from './routes/_root.introduction'
import { Route as RootDashboardRouteImport } from './routes/_root.dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgetPasswordRouteImport } from './routes/_auth.forgetPassword'
import { Route as RootMaterialEditorIndexRouteImport } from './routes/_root.material-editor.index'
import { Route as RootDashboardIndexRouteImport } from './routes/_root.dashboard.index'
import { Route as RootBlockPackEditorBlockPackIdRouteImport } from './routes/_root.block-pack-editor.$blockPackId'
import { Route as AuthRedirectXRouteImport } from './routes/_auth.redirect.x'
import { Route as AuthRedirectGoogleRouteImport } from './routes/_auth.redirect.google'
import { Route as AuthRedirectErrorRouteImport } from './routes/_auth.redirect.error'
import { Route as RootBlockPackEditorBlockPackIdIndexRouteImport } from './routes/_root.block-pack-editor.$blockPackId.index'
import { Route as RootMaterialEditorTextbookMaterialIdRouteImport } from './routes/_root.material-editor.textbook.$materialId'
import { Route as RootMaterialEditorNotebookMaterialIdRouteImport } from './routes/_root.material-editor.notebook.$materialId'

const RootRoute = RootRouteImport.update({
  id: '/_root',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RootPrivacyPolicyRoute = RootPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => RootRoute,
} as any)
const RootPlaygroundRoute = RootPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => RootRoute,
} as any)
const RootMaterialEditorRoute = RootMaterialEditorRouteImport.update({
  id: '/material-editor',
  path: '/material-editor',
  getParentRoute: () => RootRoute,
} as any)
const RootIntroductionRoute = RootIntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => RootRoute,
} as any)
const RootDashboardRoute = RootDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RootRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forgetPassword',
  path: '/forgetPassword',
  getParentRoute: () => AuthRoute,
} as any)
const RootMaterialEditorIndexRoute = RootMaterialEditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootMaterialEditorRoute,
} as any)
const RootDashboardIndexRoute = RootDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootDashboardRoute,
} as any)
const RootBlockPackEditorBlockPackIdRoute =
  RootBlockPackEditorBlockPackIdRouteImport.update({
    id: '/block-pack-editor/$blockPackId',
    path: '/block-pack-editor/$blockPackId',
    getParentRoute: () => RootRoute,
  } as any)
const AuthRedirectXRoute = AuthRedirectXRouteImport.update({
  id: '/redirect/x',
  path: '/redirect/x',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRedirectGoogleRoute = AuthRedirectGoogleRouteImport.update({
  id: '/redirect/google',
  path: '/redirect/google',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRedirectErrorRoute = AuthRedirectErrorRouteImport.update({
  id: '/redirect/error',
  path: '/redirect/error',
  getParentRoute: () => AuthRoute,
} as any)
const RootBlockPackEditorBlockPackIdIndexRoute =
  RootBlockPackEditorBlockPackIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RootBlockPackEditorBlockPackIdRoute,
  } as any)
const RootMaterialEditorTextbookMaterialIdRoute =
  RootMaterialEditorTextbookMaterialIdRouteImport.update({
    id: '/textbook/$materialId',
    path: '/textbook/$materialId',
    getParentRoute: () => RootMaterialEditorRoute,
  } as any)
const RootMaterialEditorNotebookMaterialIdRoute =
  RootMaterialEditorNotebookMaterialIdRouteImport.update({
    id: '/notebook/$materialId',
    path: '/notebook/$materialId',
    getParentRoute: () => RootMaterialEditorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgetPassword': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof RootDashboardRouteWithChildren
  '/introduction': typeof RootIntroductionRoute
  '/material-editor': typeof RootMaterialEditorRouteWithChildren
  '/playground': typeof RootPlaygroundRoute
  '/privacy-policy': typeof RootPrivacyPolicyRoute
  '/redirect/error': typeof AuthRedirectErrorRoute
  '/redirect/google': typeof AuthRedirectGoogleRoute
  '/redirect/x': typeof AuthRedirectXRoute
  '/block-pack-editor/$blockPackId': typeof RootBlockPackEditorBlockPackIdRouteWithChildren
  '/dashboard/': typeof RootDashboardIndexRoute
  '/material-editor/': typeof RootMaterialEditorIndexRoute
  '/material-editor/notebook/$materialId': typeof RootMaterialEditorNotebookMaterialIdRoute
  '/material-editor/textbook/$materialId': typeof RootMaterialEditorTextbookMaterialIdRoute
  '/block-pack-editor/$blockPackId/': typeof RootBlockPackEditorBlockPackIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgetPassword': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/introduction': typeof RootIntroductionRoute
  '/playground': typeof RootPlaygroundRoute
  '/privacy-policy': typeof RootPrivacyPolicyRoute
  '/redirect/error': typeof AuthRedirectErrorRoute
  '/redirect/google': typeof AuthRedirectGoogleRoute
  '/redirect/x': typeof AuthRedirectXRoute
  '/dashboard': typeof RootDashboardIndexRoute
  '/material-editor': typeof RootMaterialEditorIndexRoute
  '/material-editor/notebook/$materialId': typeof RootMaterialEditorNotebookMaterialIdRoute
  '/material-editor/textbook/$materialId': typeof RootMaterialEditorTextbookMaterialIdRoute
  '/block-pack-editor/$blockPackId': typeof RootBlockPackEditorBlockPackIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_root': typeof RootRouteWithChildren
  '/_auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_root/dashboard': typeof RootDashboardRouteWithChildren
  '/_root/introduction': typeof RootIntroductionRoute
  '/_root/material-editor': typeof RootMaterialEditorRouteWithChildren
  '/_root/playground': typeof RootPlaygroundRoute
  '/_root/privacy-policy': typeof RootPrivacyPolicyRoute
  '/_auth/redirect/error': typeof AuthRedirectErrorRoute
  '/_auth/redirect/google': typeof AuthRedirectGoogleRoute
  '/_auth/redirect/x': typeof AuthRedirectXRoute
  '/_root/block-pack-editor/$blockPackId': typeof RootBlockPackEditorBlockPackIdRouteWithChildren
  '/_root/dashboard/': typeof RootDashboardIndexRoute
  '/_root/material-editor/': typeof RootMaterialEditorIndexRoute
  '/_root/material-editor/notebook/$materialId': typeof RootMaterialEditorNotebookMaterialIdRoute
  '/_root/material-editor/textbook/$materialId': typeof RootMaterialEditorTextbookMaterialIdRoute
  '/_root/block-pack-editor/$blockPackId/': typeof RootBlockPackEditorBlockPackIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgetPassword'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/introduction'
    | '/material-editor'
    | '/playground'
    | '/privacy-policy'
    | '/redirect/error'
    | '/redirect/google'
    | '/redirect/x'
    | '/block-pack-editor/$blockPackId'
    | '/dashboard/'
    | '/material-editor/'
    | '/material-editor/notebook/$materialId'
    | '/material-editor/textbook/$materialId'
    | '/block-pack-editor/$blockPackId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgetPassword'
    | '/login'
    | '/register'
    | '/introduction'
    | '/playground'
    | '/privacy-policy'
    | '/redirect/error'
    | '/redirect/google'
    | '/redirect/x'
    | '/dashboard'
    | '/material-editor'
    | '/material-editor/notebook/$materialId'
    | '/material-editor/textbook/$materialId'
    | '/block-pack-editor/$blockPackId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_root'
    | '/_auth/forgetPassword'
    | '/_auth/login'
    | '/_auth/register'
    | '/_root/dashboard'
    | '/_root/introduction'
    | '/_root/material-editor'
    | '/_root/playground'
    | '/_root/privacy-policy'
    | '/_auth/redirect/error'
    | '/_auth/redirect/google'
    | '/_auth/redirect/x'
    | '/_root/block-pack-editor/$blockPackId'
    | '/_root/dashboard/'
    | '/_root/material-editor/'
    | '/_root/material-editor/notebook/$materialId'
    | '/_root/material-editor/textbook/$materialId'
    | '/_root/block-pack-editor/$blockPackId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  RootRoute: typeof RootRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_root': {
      id: '/_root'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root/privacy-policy': {
      id: '/_root/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof RootPrivacyPolicyRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/playground': {
      id: '/_root/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof RootPlaygroundRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/material-editor': {
      id: '/_root/material-editor'
      path: '/material-editor'
      fullPath: '/material-editor'
      preLoaderRoute: typeof RootMaterialEditorRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/introduction': {
      id: '/_root/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof RootIntroductionRouteImport
      parentRoute: typeof RootRoute
    }
    '/_root/dashboard': {
      id: '/_root/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof RootDashboardRouteImport
      parentRoute: typeof RootRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgetPassword': {
      id: '/_auth/forgetPassword'
      path: '/forgetPassword'
      fullPath: '/forgetPassword'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_root/material-editor/': {
      id: '/_root/material-editor/'
      path: '/'
      fullPath: '/material-editor/'
      preLoaderRoute: typeof RootMaterialEditorIndexRouteImport
      parentRoute: typeof RootMaterialEditorRoute
    }
    '/_root/dashboard/': {
      id: '/_root/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof RootDashboardIndexRouteImport
      parentRoute: typeof RootDashboardRoute
    }
    '/_root/block-pack-editor/$blockPackId': {
      id: '/_root/block-pack-editor/$blockPackId'
      path: '/block-pack-editor/$blockPackId'
      fullPath: '/block-pack-editor/$blockPackId'
      preLoaderRoute: typeof RootBlockPackEditorBlockPackIdRouteImport
      parentRoute: typeof RootRoute
    }
    '/_auth/redirect/x': {
      id: '/_auth/redirect/x'
      path: '/redirect/x'
      fullPath: '/redirect/x'
      preLoaderRoute: typeof AuthRedirectXRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/redirect/google': {
      id: '/_auth/redirect/google'
      path: '/redirect/google'
      fullPath: '/redirect/google'
      preLoaderRoute: typeof AuthRedirectGoogleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/redirect/error': {
      id: '/_auth/redirect/error'
      path: '/redirect/error'
      fullPath: '/redirect/error'
      preLoaderRoute: typeof AuthRedirectErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_root/block-pack-editor/$blockPackId/': {
      id: '/_root/block-pack-editor/$blockPackId/'
      path: '/'
      fullPath: '/block-pack-editor/$blockPackId/'
      preLoaderRoute: typeof RootBlockPackEditorBlockPackIdIndexRouteImport
      parentRoute: typeof RootBlockPackEditorBlockPackIdRoute
    }
    '/_root/material-editor/textbook/$materialId': {
      id: '/_root/material-editor/textbook/$materialId'
      path: '/textbook/$materialId'
      fullPath: '/material-editor/textbook/$materialId'
      preLoaderRoute: typeof RootMaterialEditorTextbookMaterialIdRouteImport
      parentRoute: typeof RootMaterialEditorRoute
    }
    '/_root/material-editor/notebook/$materialId': {
      id: '/_root/material-editor/notebook/$materialId'
      path: '/notebook/$materialId'
      fullPath: '/material-editor/notebook/$materialId'
      preLoaderRoute: typeof RootMaterialEditorNotebookMaterialIdRouteImport
      parentRoute: typeof RootMaterialEditorRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRedirectErrorRoute: typeof AuthRedirectErrorRoute
  AuthRedirectGoogleRoute: typeof AuthRedirectGoogleRoute
  AuthRedirectXRoute: typeof AuthRedirectXRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRedirectErrorRoute: AuthRedirectErrorRoute,
  AuthRedirectGoogleRoute: AuthRedirectGoogleRoute,
  AuthRedirectXRoute: AuthRedirectXRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface RootDashboardRouteChildren {
  RootDashboardIndexRoute: typeof RootDashboardIndexRoute
}

const RootDashboardRouteChildren: RootDashboardRouteChildren = {
  RootDashboardIndexRoute: RootDashboardIndexRoute,
}

const RootDashboardRouteWithChildren = RootDashboardRoute._addFileChildren(
  RootDashboardRouteChildren,
)

interface RootMaterialEditorRouteChildren {
  RootMaterialEditorIndexRoute: typeof RootMaterialEditorIndexRoute
  RootMaterialEditorNotebookMaterialIdRoute: typeof RootMaterialEditorNotebookMaterialIdRoute
  RootMaterialEditorTextbookMaterialIdRoute: typeof RootMaterialEditorTextbookMaterialIdRoute
}

const RootMaterialEditorRouteChildren: RootMaterialEditorRouteChildren = {
  RootMaterialEditorIndexRoute: RootMaterialEditorIndexRoute,
  RootMaterialEditorNotebookMaterialIdRoute:
    RootMaterialEditorNotebookMaterialIdRoute,
  RootMaterialEditorTextbookMaterialIdRoute:
    RootMaterialEditorTextbookMaterialIdRoute,
}

const RootMaterialEditorRouteWithChildren =
  RootMaterialEditorRoute._addFileChildren(RootMaterialEditorRouteChildren)

interface RootBlockPackEditorBlockPackIdRouteChildren {
  RootBlockPackEditorBlockPackIdIndexRoute: typeof RootBlockPackEditorBlockPackIdIndexRoute
}

const RootBlockPackEditorBlockPackIdRouteChildren: RootBlockPackEditorBlockPackIdRouteChildren =
  {
    RootBlockPackEditorBlockPackIdIndexRoute:
      RootBlockPackEditorBlockPackIdIndexRoute,
  }

const RootBlockPackEditorBlockPackIdRouteWithChildren =
  RootBlockPackEditorBlockPackIdRoute._addFileChildren(
    RootBlockPackEditorBlockPackIdRouteChildren,
  )

interface RootRouteChildren {
  RootDashboardRoute: typeof RootDashboardRouteWithChildren
  RootIntroductionRoute: typeof RootIntroductionRoute
  RootMaterialEditorRoute: typeof RootMaterialEditorRouteWithChildren
  RootPlaygroundRoute: typeof RootPlaygroundRoute
  RootPrivacyPolicyRoute: typeof RootPrivacyPolicyRoute
  RootBlockPackEditorBlockPackIdRoute: typeof RootBlockPackEditorBlockPackIdRouteWithChildren
}

const RootRouteChildren: RootRouteChildren = {
  RootDashboardRoute: RootDashboardRouteWithChildren,
  RootIntroductionRoute: RootIntroductionRoute,
  RootMaterialEditorRoute: RootMaterialEditorRouteWithChildren,
  RootPlaygroundRoute: RootPlaygroundRoute,
  RootPrivacyPolicyRoute: RootPrivacyPolicyRoute,
  RootBlockPackEditorBlockPackIdRoute:
    RootBlockPackEditorBlockPackIdRouteWithChildren,
}

const RootRouteWithChildren = RootRoute._addFileChildren(RootRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  RootRoute: RootRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
